### ISSUE TITLE
`npm build:modules` fails in interbit-ui-components

### ISSUE THREAD

**Issue by jared-dykstra** [interbit/interbit#690] opened 2018-09-11 20:38 UTC
Using:
* interbit/interbit - master @ 5ab5c49d1056b2b88fbb0984fb609dadbbbadd61 
* node v10.9.0
* npm 6.4.0

To reproduce, follow the steps here: https://docs.interbit.io/getting-started/install.html

Error: 
```
lerna ERR! ERROR in C:/github/helixapps/interbit/node_modules/@babel/runtime-corejs2/core-js/array/is-array.js
lerna ERR! Module not found: Error: Can't resolve 'core-js/library/fn/array/is-array' in 'C:\github\helixapps\interbit\node_modules\@babel\runtime-corejs2\core-js\array'
lerna ERR!  @ C:/github/helixapps/interbit/node_modules/@babel/runtime-corejs2/core-js/array/is-array.js 1:17-61
lerna ERR!  @ C:/github/helixapps/interbit/node_modules/react-bootstrap/es/OverlayTrigger.js
lerna ERR!  @ C:/github/helixapps/interbit/node_modules/react-bootstrap/es/index.js
lerna ERR!  @ ./src/components/NotFound.js
lerna ERR!  @ ./src/index.js
lerna ERR!
lerna ERR! ERROR in C:/github/helixapps/interbit/node_modules/@babel/runtime-corejs2/core-js/parse-int.js
lerna ERR! Module not found: Error: Can't resolve 'core-js/library/fn/parse-int' in 'C:\github\helixapps\interbit\node_modules\@babel\runtime-corejs2\core-js'
lerna ERR!  @ C:/github/helixapps/interbit/node_modules/@babel/runtime-corejs2/core-js/parse-int.js 1:17-56
lerna ERR!  @ C:/github/helixapps/interbit/node_modules/react-bootstrap/es/Collapse.js
lerna ERR!  @ C:/github/helixapps/interbit/node_modules/react-bootstrap/es/index.js
lerna ERR!  @ ./src/components/NotFound.js
lerna ERR!  @ ./src/index.js
lerna ERR!
```

**Comment by jared-dykstra** [comment] 2018-09-11 20:39
Looks suspiciously similar to what is described here:  https://github.com/react-bootstrap/react-bootstrap/issues/3231

**Comment by jared-dykstra** [comment] 2018-09-11 20:46
Confirmed that this isn't isolated to master, and that it also affects https://github.com/interbit/interbit/releases/tag/v0.4.46

**Comment by jared-dykstra** [comment] 2018-09-11 20:54
I checked `interbit/node_modules/babel-runtime` and I have version 6.26.0, so [the previous comment](https://github.com/interbit/interbit/issues/690#issuecomment-420417414) is probably irrelevant

**Comment by nicholeous** [comment] 2018-09-12 16:26
Refer to PR #695

**Comment by nicholeous** [comment] 2018-09-13 16:51
No longer reproducible since merge of #695 and making a release. Closing.

**Closed by nicholeous** 2018-09-13 16:51 UTC
Labels: bug
